### ISSUE TITLE
FYI/question

### ISSUE THREAD

**Issue by alphapapa** [ndw/emacs-gfs#1]
Hi,

A quick FYI or question, if I may: you mention that `text-scale` only works on the `default` face, so it doesn't scale other faces.  I may be mistaken, but I think the idea is that all faces should inherit from `default` or another face that does (i.e. a chain of inheritance that ultimately arrives at `default`).  So if that doesn't work for you, it might be that you have some customized or themed faces that break that inheritance chain.

On the other hand, I may be wrong, in which case this library could be very useful.  :)

**Comment by ndw** [comment]
I suppose it's possible that scaling the default face works for everyone else and it's just something I've broken locally. If you can demonstrate that's the case, I'll investigate. In the meantime, this works for me :-)
